name       : lsd2dsl
version    : 0.5.4
release    : 1
source     :
    - https://github.com/nongeneric/lsd2dsl/archive/refs/tags/v0.5.4.tar.gz : dadf98785f26ad6063c818be576ce59d61265f3b9d1e0bab319a9bab4b162b43
license    : MIT
component  : programming.tools
summary    : Lingvo dictionaries decompiler
homepage   : https://rcebits.com/lsd2dsl/index.html
description: |
    ABBYY Lingvo dictionaries decompiler.
builddeps  :
    - pkgconfig(Qt5WebKitWidgets)
    - pkgconfig(sndfile)
    - pkgconfig(vorbisfile)
    - gtest-devel
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/compile.patch
    %cmake
build      : |
    %make
install    : |
    install -Dm 00755 console/lsd2dsl $installdir/usr/bin/lsd2dsl
    install -Dm 00755 gui/lsd2dsl-qtgui $installdir/usr/bin/lsd2dsl-qt
